version: '3'

services:
  database:
    image: 'postgres'
    environment:
      - POSTGRES_DB=movieDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - userdata-data:/var/lib/postgresql/data/

  backend:
    image: 'hoffrenm/easpringapi'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/movieDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - '8080:8080'
    depends_on:
      - database

volumes:
  userdata-data:
